version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      # Define the directory where Traefik will look for additional configuration files
      - "--providers.file.directory=/etc/traefik/"
      # Enable watching for changes in the configuration files
      - "--providers.file.watch=true"
      # Define the HTTP entry point, listening on port 80
      - "--entrypoints.http.address=:80"
      # Define the HTTPS entry point, listening on port 443
      - "--entrypoints.https.address=:443"
      # Enable the Traefik dashboard
      - "--api.dashboard=true"
      # Allow insecure access to the API and dashboard (only for development)
      - "--api.insecure=true"
      # Redirect all HTTP traffic to HTTPS
      - "--entrypoints.http.http.redirections.entryPoint.to=https"
      # Set the redirection scheme to HTTPS
      - "--entrypoints.http.http.redirections.entryPoint.scheme=https"
      # Make the redirection permanent (301 redirect)
      - "--entrypoints.http.http.redirections.entryPoint.permanent=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./certs:/etc/traefik:ro
    restart: always

  n8n:
    image: n8nio/n8n
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8npassword
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=adminpassword
      - N8N_HOST=myautomationapp.duckdns.org
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://myautomationapp.duckdns.org/
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`myautomationapp.duckdns.org`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8npassword
      - POSTGRES_DB=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  n8n_data:
  postgres_data:
