entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:
        certificates:
          - certFile: "/certs/selfsigned.crt"
            keyFile: "/certs/selfsigned.key"
